"""
Markdown Report Generator for Walk-Forward OS.
Generates comprehensive walk-forward validation and data leakage reports.
"""

from typing import Dict, Any, List


class WalkForwardReportGenerator:
    """Generates detailed Markdown reports for Walk-Forward OOS evaluation and Data Leakage audits."""

    @staticmethod
    def generate_walk_forward_report(val_dict: Dict[str, Any]) -> str:
        res = val_dict
        method = res.get("method", "EXPANDING")
        status = res.get("status", "COMPLETED")
        metrics = res.get("oos_metrics", {})
        robustness = res.get("robustness_metrics", {})
        stability = robustness.get("performance_stability", {})
        leakage = res.get("leakage_audit", {})
        windows = res.get("windows", [])

        md = []
        md.append(f"# Walk-Forward & Out-of-Sample Validation Report ({res.get('validation_id', 'VAL-001')})")
        md.append(f"**Experiment ID**: `{res.get('experiment_id')}` | **Status**: `{status}` | **Method**: `{method}`")
        md.append(f"**Config Hash**: `{res.get('config_hash')}` | **Timestamp**: `{res.get('timestamp')}`\n")

        md.append("## Executive Summary")
        md.append(f"- **Total Walk-Forward Folds**: `{len(windows)}`")
        md.append(f"- **Mean Out-of-Sample Sharpe**: `{metrics.get('mean_out_of_sample_sharpe', 0.0):.2f}`")
        md.append(f"- **OOS Sharpe Std Dev**: `{metrics.get('std_out_of_sample_sharpe', 0.0):.2f}`")
        md.append(f"- **Positive Fold Ratio**: `{stability.get('positive_fold_ratio', 0.0) * 100:.1f}%`")
        md.append(f"- **Stability Score**: `{stability.get('stability_score', 0.0):.2f}` (`{stability.get('status', 'N/A')}`)")
        md.append(f"- **Data Leakage Status**: `{leakage.get('status', 'CLEAN')}`\n")

        md.append("## Out-of-Sample Performance Metrics")
        md.append("| Metric | Value |")
        md.append("| :--- | :--- |")
        md.append(f"| Mean OOS Sharpe | {metrics.get('mean_out_of_sample_sharpe', 0.0):.2f} |")
        md.append(f"| Min OOS Sharpe | {metrics.get('min_out_of_sample_sharpe', 0.0):.2f} |")
        md.append(f"| Max OOS Sharpe | {metrics.get('max_out_of_sample_sharpe', 0.0):.2f} |")
        md.append(f"| Mean Annualized Return | {metrics.get('mean_annualized_return', 0.0) * 100:.2f}% |")
        md.append(f"| Mean Prediction MAE | {metrics.get('mean_mae', 0.0):.6f} |")
        md.append(f"| Mean Prediction RMSE | {metrics.get('mean_rmse', 0.0):.6f} |\n")

        md.append("## Walk-Forward Fold Details")
        md.append("| Fold | Train Range | Val Range | Test Range | OOS Sharpe | Purged | Embargoed |")
        md.append("| :--- | :--- | :--- | :--- | :--- | :--- | :--- |")
        for w in windows:
            fid = w.get("window_id", "")
            tr = f"{w.get('train_start')} → {w.get('train_end')}"
            val_r = f"{w.get('validation_start')} → {w.get('validation_end')}"
            te = f"{w.get('test_start')} → {w.get('test_end')}"
            ev = w.get("evaluation", {}).get("trading_metrics", {})
            s = ev.get("sharpe_ratio", 0.0)
            md.append(f"| {fid} | {tr} | {val_r} | {te} | {s:.2f} | {w.get('purged_samples', 0)} | {w.get('embargoed_samples', 0)} |")

        md.append("\n## Data Leakage Audit Summary")
        md.append(f"- **Audit Status**: `{leakage.get('status', 'CLEAN')}`")
        md.append(f"- **Total Issues Found**: `{leakage.get('total_issues', 0)}`")
        if leakage.get("issues"):
            md.append("\n### Detected Leakage Issues")
            for issue in leakage["issues"]:
                md.append(f"- ⚠️ `{issue}`")

        md.append("\n---\n*Report generated by Walk-Forward Validation OS Engine.*")
        return "\n".join(md)
