"""
Base Task Contract for Orchestrator Pipeline Tasks.
"""

from abc import ABC, abstractmethod
from typing import Dict, Any, List


class BaseTask(ABC):
    """
    Abstract Base Class for Workflow Tasks.
    Every task implements:
    - run(context): Executes task logic and updates context/artifacts.
    - validate(context): Pre-execution gate validation.
    - outputs(): List of expected output keys or artifact types.
    """

    def __init__(self, task_id: str, name: str, configuration: Dict[str, Any] = None):
        self.task_id = task_id
        self.name = name
        self.configuration = configuration or {}

    @abstractmethod
    def run(self, context: Dict[str, Any]) -> Dict[str, Any]:
        """Execute task logic and return updated dictionary context."""
        pass

    @abstractmethod
    def validate(self, context: Dict[str, Any]) -> bool:
        """Validate context before running task."""
        pass

    @abstractmethod
    def outputs(self) -> List[str]:
        """List of output artifact types generated by task."""
        pass
